services:
  mongo:
    image: mongo:7
    container_name: task-manager-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: task_manager_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-manager-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpassword@mongo:27017/task_manager_db?authSource=admin
      APP_CORS_ALLOWED_ORIGINS: http://localhost:4200,http://localhost:3000,http://localhost:5173
    ports:
      - "8082:8082"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mongo-data:
